version: '3.8'

services:
  db_transactions_read:
    image: mongo:5.0.6-focal
    container_name: db_transactions_read
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb_trans:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rpwd
      MONGO_INITDB_DATABASE: app
  
  db_big_data:
    image: mongo:5.0.6-focal
    container_name: db_big_data
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data/mongodb_bigdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rpwd
      MONGO_INITDB_DATABASE: app
